onlyBuiltDependencies:
  - "@google/genai"
  - canvas
  - esbuild
  - protobufjs
  - sharp
  - unrs-resolver
allowBuilds:
  "@google/genai": true
  canvas: true
  esbuild: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
