"use client";
import { MessageSquarePlus, Pencil, Trash2 } from "lucide-react";
import type { Conversation } from "@/lib/assistant/domain";

export function ConversationSidebar({ conversations, selectedId, hasMore, transitionPending, onLoadMore, onSelect, onCreate, onRename, onDelete }: Readonly<{ conversations: readonly Conversation[]; selectedId?: string; hasMore: boolean; transitionPending: boolean; onLoadMore(): void; onSelect(id: string): void; onCreate(): void; onRename(title: string): void; onDelete(): void }>) {
  const selectedReadOnly = conversations.find((conversation) => conversation.id === selectedId)?.status === "archived_analysis_deleted";
  return <nav aria-label="Conversaciones" className="flex h-full min-h-0 flex-col bg-white">
    <div className="border-b border-line p-3"><button type="button" className="btn-primary w-full disabled:cursor-not-allowed disabled:opacity-40" disabled={transitionPending} onClick={onCreate}><MessageSquarePlus aria-hidden="true" className="size-4" />Nueva conversación</button></div>
    <ul data-testid="conversation-list" className="min-h-0 flex-1 space-y-1 overflow-y-auto p-2">{conversations.map((conversation) => <li key={conversation.id}><button type="button" aria-current={conversation.id === selectedId ? "page" : undefined} disabled={transitionPending} className={`min-h-11 w-full rounded-xl px-3 py-2 text-left text-sm transition-colors duration-180 disabled:cursor-not-allowed disabled:opacity-40 ${conversation.id === selectedId ? "bg-slate-900 font-semibold text-white" : "text-slate-700 hover:bg-slate-100"}`} onClick={() => onSelect(conversation.id)}><span className="block truncate">{conversation.title}</span>{conversation.status === "archived_analysis_deleted" ? <span className="mt-0.5 block text-xs text-muted">Analisis eliminado</span> : null}</button></li>)}</ul>
    {hasMore ? <button type="button" className="mx-3 mb-2 min-h-11 rounded-xl text-sm font-bold text-primary hover:bg-blue-50" onClick={onLoadMore}>Cargar más conversaciones</button> : null}
    {selectedId ? <div className="grid grid-cols-2 gap-1 border-t border-line p-2"><button type="button" disabled={selectedReadOnly || transitionPending} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-xl text-muted hover:bg-slate-100 disabled:cursor-not-allowed disabled:opacity-40" aria-label="Renombrar conversacion" onClick={() => { const value = window.prompt("Nuevo nombre de la conversacion"); if (value?.trim()) onRename(value); }}><Pencil aria-hidden="true" className="size-4" /></button><button type="button" disabled={transitionPending} className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-xl text-danger hover:bg-red-50 disabled:cursor-not-allowed disabled:opacity-40" aria-label="Eliminar conversacion" onClick={onDelete}><Trash2 aria-hidden="true" className="size-4" /></button></div> : null}
  </nav>;
}
