"use client";
import { Check, Users, X } from "lucide-react";
import { useMemo, useState } from "react";

export function PersonContextPicker({ availableIds, associatedIds, primaryId, disabled = false, onAdd, onRemove, onPrimary, onOpen }: Readonly<{ availableIds: readonly string[]; associatedIds: readonly string[]; primaryId?: string; disabled?: boolean; onAdd(id: string): void; onRemove(id: string): void; onPrimary(id: string): void; onOpen?(id: string): void }>) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState("");
  const unique = [...new Set(associatedIds)]; const visible = unique.slice(0, 3);
  const ids = useMemo(() => [...availableIds].sort((a, b) => Number(unique.includes(b)) - Number(unique.includes(a)) || a.localeCompare(b)).filter((id) => id.includes(query.trim())), [availableIds, query, unique]);
  return <section className="flex min-h-0 flex-col gap-2">
    <div className="flex flex-wrap gap-1.5" aria-label="Personas asociadas resumidas">{visible.map((id) => <span key={id} className={`rounded-full px-2 py-1 text-xs font-bold ${id === primaryId ? "bg-blue-100 text-blue-800" : "bg-slate-100 text-slate-700"}`}>{id}</span>)}{unique.length > visible.length ? <span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-bold text-slate-700">+ {unique.length - visible.length}</span> : null}</div>
    {primaryId ? <p className="text-xs font-medium text-muted">Principal: matrícula {primaryId}</p> : null}
    <div className="flex gap-2"><button type="button" className="btn-secondary flex-1" aria-expanded={open} onClick={() => setOpen((value) => !value)}><Users aria-hidden="true" className="size-4" />Gestionar personas asociadas</button>{unique.length ? <button type="button" className="btn-secondary" aria-label="Limpiar personas asociadas" disabled={disabled} onClick={() => unique.forEach(onRemove)}><X aria-hidden="true" className="size-4" /></button> : null}</div>
    {open ? <fieldset className="flex min-h-0 flex-1 flex-col rounded-xl bg-slate-50 p-2" aria-label="Personas asociadas"><legend className="sr-only">Personas asociadas</legend><input className="filter-control sticky top-0 mb-2" aria-label="Buscar personas asociadas" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Buscar matrícula" /><div className="min-h-0 max-h-[min(45dvh,24rem)] space-y-1 overflow-y-auto pr-1">{ids.map((id) => { const checked = unique.includes(id); return <div key={id} className="flex min-h-11 items-center gap-2 rounded-lg px-1 hover:bg-white"><label className="flex min-h-11 min-w-0 flex-1 items-center gap-2 text-sm font-medium text-ink"><input aria-label={`Matrícula ${id}`} type="checkbox" className="size-5" disabled={disabled} checked={checked} onClick={(event) => event.stopPropagation()} onChange={() => checked ? onRemove(id) : onAdd(id)} />Matrícula {id}</label>{onOpen ? <button type="button" className="text-xs font-bold text-primary" onClick={() => onOpen(id)}>Ver ficha</button> : null}<button type="button" className="inline-flex min-h-11 min-w-11 items-center justify-center rounded-xl text-primary hover:bg-blue-100 disabled:text-muted" disabled={disabled || id === primaryId || !checked} aria-label={`Marcar matrícula ${id} como principal`} onClick={() => onPrimary(id)}><Check aria-hidden="true" className="size-4" /></button></div>; })}</div></fieldset> : null}
  </section>;
}
