import type { ReactNode } from "react";
import type { SourceReference } from "@/lib/assistant/domain";
import type { PersonAnalysisEvidence } from "@/lib/assistant/tools/personEvidence";
import { formatEuro } from "@/lib/utils/money";

const labels: Record<string, string> = { personId: "Matrícula", totalDifference: "Diferencia total", registroTotal: "Total Registro Retributivo", pdfTotal: "Total recibos", workplace: "Centro de trabajo", position: "Puesto", category: "Categoría", professionalGroup: "Grupo profesional", valuation: "Valoración", family: "Familia", personalCategoryGroup: "Agrupación profesional", status: "Estado", period: "Periodo", salary: "Salario", salaryComplement: "Complemento salarial", extraSalary: "Extrasalarial", total: "Total", normalizedPlusVariables: "Normalizado más variables", normalized: "Normalizado", periodComplete: "Periodo completo", lastSituation: "Última situación", salaryComplementVariable: "Variable de complemento salarial", extraSalaryVariable: "Variable extrasalarial", salaryPpe: "Salario PPE", salaryComplementPpe: "Complemento PPE", salaryIt: "Salario IT", salaryComplementIt: "Complemento IT", excelBreakdownDiffs: "Diferencias del desglose", realPdf: "Total real de recibos", diffPdfVsPeriodComplete: "Recibos frente a periodo completo", diffPdfVsNormalizedPlusVariables: "Recibos frente a normalizado más variables", diffPdfVsNormalized: "Recibos frente a normalizado", irpfBaseAccumulated: "Base IRPF acumulada", irpfFeeAccumulated: "Cuota IRPF acumulada", ssFeeAccumulated: "Seguridad Social acumulada" };
function Metric({ label, value, tone = "text-ink" }: Readonly<{ label: string; value: ReactNode; tone?: string }>) { return <div className="min-w-0 rounded-xl bg-slate-50 p-3 ring-1 ring-slate-200/80"><p className="text-[0.6875rem] font-bold uppercase tracking-wide text-muted">{label}</p><p className={`mt-1 break-words text-base font-bold ${tone}`}>{value}</p></div>; }

function flattenReadable(value: unknown, prefix = ""): Array<{ key: string; label: string; value: string }> {
  if (!value || typeof value !== "object") return [];
  return Object.entries(value as Record<string, unknown>).flatMap(([key, item]) => {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof item === "number") return [{ key: path, label: labels[key] ?? key.replace(/([A-Z])/g, " $1"), value: formatEuro(item) }];
    if (typeof item === "string" || typeof item === "boolean") return [{ key: path, label: labels[key] ?? key.replace(/([A-Z])/g, " $1"), value: String(item) }];
    return flattenReadable(item, path);
  });
}
function ReadableData({ value }: Readonly<{ value: unknown }>) { const entries = flattenReadable(value); return entries.length ? <dl className="grid gap-2 sm:grid-cols-2">{entries.map((entry) => <div key={entry.key} className="rounded-lg bg-slate-50 p-2"><dt className="text-xs text-muted">{entry.label}</dt><dd className="break-words font-semibold text-ink">{entry.value}</dd></div>)}</dl> : <p className="text-sm text-muted">No hay datos adicionales disponibles.</p>; }

function PersonEvidence({ evidence }: Readonly<{ evidence: PersonAnalysisEvidence }>) {
  const differences = evidence.comparisons.filter((item) => Math.abs(item.adjustedDifference ?? item.difference) > 0.009 || item.status !== "OK");
  const context = Object.entries(evidence.laborContext).filter(([, value]) => Boolean(value));
  return <div className="space-y-6 text-sm">
    <section aria-labelledby="source-summary"><h3 id="source-summary" className="font-bold text-ink">Resumen</h3><div className="mt-3 grid grid-cols-2 gap-2 xl:grid-cols-4"><Metric label="Registro Retributivo" value={formatEuro(evidence.totals.registro)} /><Metric label="Recibos" value={formatEuro(evidence.totals.payroll)} /><Metric label="Diferencia" value={formatEuro(evidence.totals.difference)} tone={Math.abs(evidence.totals.difference) > 0.009 ? "text-danger" : "text-emerald-700"} /><Metric label="Estado" value={evidence.status} /></div><div className="mt-3 grid gap-2 sm:grid-cols-3"><Metric label="Salario" value={formatEuro(evidence.blocks.salary.difference)} /><Metric label="Complemento salarial" value={formatEuro(evidence.blocks.salaryComplement.difference)} /><Metric label="Extrasalarial" value={formatEuro(evidence.blocks.extraSalary.difference)} tone={Math.abs(evidence.blocks.extraSalary.difference) > 0.009 ? "text-danger" : "text-ink"} /></div></section>
    <section aria-labelledby="source-differences"><div className="flex flex-wrap items-end justify-between gap-2"><h3 id="source-differences" className="font-bold text-ink">Conceptos descuadrados</h3><span className="rounded-full bg-red-50 px-2 py-1 text-xs font-bold text-danger">{differences.length} detectados</span></div>{differences.length ? <div className="mt-3 space-y-3">{differences.map((item, index) => <article key={`${item.registroCode}-${item.pdfConcept ?? index}`} className="rounded-xl border border-red-100 bg-red-50/40 p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-bold text-ink">{item.pdfConcept ?? item.registroCode}</p><p className="text-xs text-muted">{item.block} · código {item.registroCode}</p></div><span className="rounded-full bg-white px-2 py-1 text-xs font-bold text-red-700 ring-1 ring-red-200">{formatEuro(item.difference)}</span></div><dl className="mt-3 grid grid-cols-3 gap-2 text-xs"><div><dt className="text-muted">Registro</dt><dd className="font-bold text-ink">{formatEuro(item.registroAmount)}</dd></div><div><dt className="text-muted">Recibos</dt><dd className="font-bold text-ink">{formatEuro(item.payrollAmount)}</dd></div><div><dt className="text-muted">Diferencia</dt><dd className="font-bold text-danger">{formatEuro(item.difference)}</dd></div></dl><div className="mt-3 border-t border-red-100 pt-3"><div className="flex flex-wrap items-center gap-2"><p className="font-bold text-ink">Causa probable: {item.cause.label}</p><span className="rounded-full bg-blue-50 px-2 py-0.5 text-xs font-bold text-primary">Confianza {item.cause.confidence}</span></div><p className="mt-1 text-slate-700">{item.cause.description}</p><p className="mt-2 text-xs font-semibold text-muted">Pendiente de confirmar</p><ul className="mt-1 list-disc space-y-1 pl-5 text-xs text-slate-600">{item.cause.missingEvidence.map((fact) => <li key={fact}>{fact}</li>)}</ul></div></article>)}</div> : <p className="mt-2 rounded-xl bg-emerald-50 p-3 text-emerald-800">No hay conceptos descuadrados.</p>}</section>
    {context.length ? <section><h3 className="font-bold text-ink">Contexto laboral</h3><dl className="mt-3 grid gap-2 sm:grid-cols-2">{context.map(([key, value]) => <div key={key} className="rounded-lg bg-slate-50 p-2"><dt className="text-xs text-muted">{labels[key] ?? key}</dt><dd className="break-words font-semibold text-ink">{value}</dd></div>)}</dl></section> : null}
    <section><h3 className="font-bold text-ink">Registro Retributivo</h3><div className="mt-3 overflow-hidden rounded-xl border border-line"><table className="w-full table-fixed text-left text-xs"><thead className="bg-slate-50 text-muted"><tr><th className="w-[42%] p-2">Concepto</th><th className="w-[33%] p-2">Bloque</th><th className="p-2 text-right">Importe</th></tr></thead><tbody>{evidence.registro.concepts.map((item, index) => <tr key={`${item.code}-${index}`} className="border-t border-line"><td className="break-words p-2 font-medium text-ink">{item.code}</td><td className="break-words p-2 text-muted">{item.block}</td><td className="p-2 text-right font-semibold text-ink">{formatEuro(item.amount)}</td></tr>)}</tbody></table></div></section>
    <section><h3 className="font-bold text-ink">Recibos por periodo</h3><div className="mt-3 space-y-2">{evidence.payroll.periods.map((period, index) => <details key={`${period.period}-${index}`} className="rounded-xl border border-line bg-white" open={index === 0}><summary className="cursor-pointer list-none p-3 font-bold text-ink">{period.period} <span className="ml-2 text-xs font-normal text-muted">{period.concepts.length} conceptos</span></summary><div className="border-t border-line p-3"><div className="space-y-2">{period.concepts.map((concept, conceptIndex) => <div key={`${concept.name}-${conceptIndex}`} className="grid grid-cols-[minmax(0,1fr)_auto] gap-3 text-xs"><span className="break-words text-slate-700">{concept.name}</span><span className="font-bold text-ink">{formatEuro(concept.amount)}</span></div>)}</div>{Object.keys(period.totals).length ? <dl className="mt-3 grid grid-cols-2 gap-2 border-t border-line pt-3 text-xs">{Object.entries(period.totals).map(([key, value]) => <div key={key}><dt className="text-muted">{({ totalDevengado: "Total devengado", totalDeducir: "Total deducciones", netPay: "Neto" } as Record<string, string>)[key] ?? key}</dt><dd className="font-bold text-ink">{formatEuro(value)}</dd></div>)}</dl> : null}{Object.keys(period.bases).length ? <div className="mt-3 border-t border-line pt-3"><p className="mb-2 text-xs font-bold text-muted">Bases acumuladas</p><ReadableData value={period.bases} /></div> : null}</div></details>)}</div></section>
    <section><h3 className="font-bold text-ink">Normalización y cuadre interno</h3><div className="mt-3 space-y-2"><details className="rounded-xl border border-line"><summary className="cursor-pointer p-3 font-semibold text-ink">Datos normalizados del Registro</summary><div className="border-t border-line p-3"><ReadableData value={{ normalizedPlusVariables: evidence.registro.normalizedPlusVariables, normalized: evidence.registro.normalized, periodComplete: evidence.registro.periodComplete, lastSituation: evidence.registro.lastSituation, nonNormalized: evidence.registro.nonNormalized, excelBreakdownDiffs: evidence.registro.excelBreakdownDiffs }} /></div></details><details className="rounded-xl border border-line"><summary className="cursor-pointer p-3 font-semibold text-ink">Comprobaciones de cuadre</summary><div className="border-t border-line p-3"><ReadableData value={{ cuadre: evidence.cuadre, normalizedData: evidence.normalizedData }} /></div></details></div></section>
  </div>;
}

function EvidenceSupport({ evidence }: Readonly<{ evidence: PersonAnalysisEvidence }>) {
  const differences = evidence.comparisons.filter((item) => Math.abs(item.adjustedDifference ?? item.difference) > 0.009 || item.status !== "OK");
  if (!differences.length) return null;
  return <section className="mt-6 text-sm" aria-labelledby="source-cause-context">
    <h3 id="source-cause-context" className="font-bold text-ink">Causa probable y contexto laboral</h3>
    <div className="mt-3 space-y-3">{differences.map((item, index) => <article key={`${item.registroCode}-${item.pdfConcept ?? index}-support`} className="rounded-xl border border-line p-3">
      <div className="flex flex-wrap items-center gap-2"><p className="font-bold text-ink">{item.pdfConcept ?? item.registroCode}</p><span className="rounded-full bg-blue-50 px-2 py-0.5 text-xs font-bold text-primary">Confianza {item.cause.confidence}</span></div>
      <p className="mt-2 text-slate-700">{item.cause.description}</p>
      <p className="mt-3 text-xs font-semibold text-muted">Hechos que sustentan la inferencia</p>
      <ul className="mt-1 list-disc space-y-1 pl-5 text-xs text-slate-600">{item.cause.facts.map((fact) => <li key={fact}>{fact}</li>)}</ul>
      <p className="mt-3 text-xs font-semibold text-muted">Revisión recomendada</p><p className="mt-1 text-xs text-slate-600">{item.cause.review}</p>
      {item.cohorts.length ? <div className="mt-3"><p className="text-xs font-semibold text-muted">Contexto agregado anónimo</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{item.cohorts.map((cohort) => <div key={`${cohort.dimension}-${cohort.value}`} className="rounded-lg bg-slate-50 p-2 text-xs"><p className="font-bold text-ink">{labels[cohort.dimension === "puesto" ? "position" : cohort.dimension === "categoria" ? "category" : "workplace"]}: {cohort.value}</p><p className="mt-1 text-muted">{cohort.peopleCount} personas · diferencia media {formatEuro(cohort.averageDifference)}</p></div>)}</div></div> : null}
    </article>)}</div>
  </section>;
}

function parseLegacy(excerpt: string): Record<string, unknown> | undefined { try { const value = JSON.parse(excerpt); return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : undefined; } catch { return undefined; } }
function LegacyDetails({ source }: Readonly<{ source: SourceReference }>) { const parsed = parseLegacy(source.excerpt); const entries = parsed ? Object.entries(parsed).filter(([, value]) => ["string", "number", "boolean"].includes(typeof value)) : []; return <div className="space-y-4 text-sm"><dl className="grid gap-2 sm:grid-cols-2">{source.page ? <div><dt className="text-xs text-muted">Página</dt><dd className="font-semibold">{source.page}</dd></div> : null}{source.sheet ? <div><dt className="text-xs text-muted">Hoja</dt><dd className="font-semibold">{source.sheet}</dd></div> : null}{source.period ? <div><dt className="text-xs text-muted">Periodo</dt><dd className="font-semibold">{source.period}</dd></div> : null}{entries.map(([key, value]) => <div key={key} className="min-w-0 rounded-lg bg-slate-50 p-2"><dt className="text-xs text-muted">{labels[key] ?? key.replace(/([A-Z])/g, " $1")}</dt><dd className="break-words font-semibold text-ink">{String(value)}</dd></div>)}</dl>{!parsed ? <section><h3 className="font-bold text-ink">Extracto anonimizado</h3><p className="mt-2 whitespace-pre-wrap break-words text-slate-600">{source.excerpt}</p></section> : null}<details className="rounded-xl border border-line"><summary className="cursor-pointer p-3 text-xs font-bold text-muted">Extracto técnico heredado</summary><div className="border-t border-line p-3 text-xs text-slate-600">Contenido conservado para auditoría e integridad. Se presenta arriba en formato legible.</div></details></div>; }

export function SourceDetails({ source }: Readonly<{ source: SourceReference }>) { return source.presentation?.kind === "person_analysis" ? <><PersonEvidence evidence={source.presentation.evidence} /><EvidenceSupport evidence={source.presentation.evidence} /></> : <LegacyDetails source={source} />; }
